import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { data } = api.post.getAll.useQuery();

  const user = useUser();

  return (
    <>
      <Head>
        <title>Testing commit</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
        {!user.isSignedIn && <SignInButton mode="modal" />}
        {user.isSignedIn && <SignOutButton />}
        <div>
          {data?.map((item, index) => (
            <div key={index}>{item.content}</div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
